services:
  db-mysql:
    image: mysql:latest
    restart: always
    container_name: db-mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: dpe
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - "3308:3306"
    volumes:
      - dpe-db:/var/lib/mysql

  activemq:
    image: apache/activemq-classic:5.18.6
    container_name: activemq
    ports:
      - "61616:61616" # Port für JMS
      - "8161:8161"   # Port für die Admin-Oberfläche
    environment:
      - ACTIVEMQ_USER=admin
      - ACTIVEMQ_PASSWORD=admin
    volumes:
      - dpe-activemq:/opt/activemq/data


volumes:
  dpe-db:
    driver: local
  dpe-activemq: